site_name: 角料文档
site_description: 角料文档
site_author: Nosy
copyright: '版权 &copy; 2018 wohugb.github.io'

repo_name: wohugb/material-docs
repo_url: https://github.com/wohugb/material-docs
edit_uri: ""

theme:
  name: material

  include_search_page: false
  search_index_only: true

  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
  extra_css: [assets/stylesheets/extra.css]
extra:
  search:
    language: 'jp'
  social:
    - type: globe
      link: http://wohugb.github.io
    - type: github-alt
      link: https://github.com/wohugb
    - type: twitter
      link: https://twitter.com/wohugb
    - type: linkedin
      link: https://linkedin.com/in/wohugb

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

pages:
  - 概述: index.md
  - 入门: getting-started.md
  - 主题: theming.md
  - 自定义主题: theming-your-components.md
  - 排版: typography.md
  - 自定义组件样式: customizing-component-styles.md
  - 自定义表单域控制: creating-a-custom-form-field-control.md
  - 海拔: elevation.md
  - 双向性: bidirectionality.md